### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by larryzhz** [edexheim/como#1]
python como/como_demo.py --dataset_type=realsense
WARNING: Using soft CircularBuffer (6144 KiB)
FEngine (64 bits) created at 0x5b7ea0e673c0 (threading is enabled)
FEngine resolved backend: OpenGL
Traceback (most recent call last):
  File "/media/zhuz/robo/como/como/como_demo.py", line 37, in <module>
    main(dataset)
  File "/media/zhuz/robo/como/como/como_demo.py", line 24, in main
    viz_window = ComoMp(viz_cfg, slam_cfg, dataset)
  File "/media/zhuz/robo/como/como/odom/multiprocessing/ComoMp.py", line 17, in __init__
    super().__init__(viz_cfg, slam_cfg, dataset)
  File "/media/zhuz/robo/como/como/gui/GuiWindow.py", line 186, in __init__
    self.setup_slam_processes(slam_cfg)
  File "/media/zhuz/robo/como/como/odom/multiprocessing/ComoMp.py", line 59, in setup_slam_processes
    self.mapping.setup()
  File "/media/zhuz/robo/como/como/odom/Mapping.py", line 56, in setup
    init_gpu(self.device)
  File "/media/zhuz/robo/como/como/utils/multiprocessing.py", line 8, in init_gpu
    init_tensor = torch.zeros((8, 192, 256), device="cpu").to(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by edexheim** [comment]
Hello,

Can you give me more details on your setup? Since it is the mapping, can you try changing the line here to use `cuda:0` instead of `cuda:1`? 
https://github.com/edexheim/como/blob/22cc209a460aaa15874221fd3b5e0b12ae998e48/config/como.yml#L27 

I will likely change that to the default.  It's also possible to put tracking on `cpu` as well.

**Comment by larryzhz** [comment]
thanks a lot for your replying, it should be the cuda version problem. I will reinstall cuda and then test. All the best.

**Comment by edexheim** [comment]
Ok, I will close this for now, but let me know if you still run into any issues after reinstalling cuda.
